// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

export function GetMap1():Promise<{[key: string]: string}>;

export function GetMap2():Promise<Array<{[key: string]: string}>>;

export function Greet(arg1:string):Promise<string>;

export function Greet1(arg1:string):Promise<string>;
