// @ts-check
// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

export function GetMap1() {
  return window['go']['main']['App']['GetMap1']();
}

export function GetMap2() {
  return window['go']['main']['App']['GetMap2']();
}

export function Greet(arg1) {
  return window['go']['main']['App']['Greet'](arg1);
}

export function Greet1(arg1) {
  return window['go']['main']['App']['Greet1'](arg1);
}
